version: '3.8'

services:
  backend:
    image: node:20
    working_dir: /app
    volumes:
      - ./backend:/app
    command: sh -c "npm install && npm run start:dev"
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/voltride

  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm start"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0

  mongo:
    image: mongo:latest
    container_name: voltride-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
